version: '3.8'

services:
  webapp1:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=cinema_user
      - MYSQL_PASSWORD=cinema_password
      - MYSQL_DATABASE=cinema_db
      - SERVER_NAME=server1

  webapp2:
    build: .
    ports:
      - "8082:8080"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=cinema_user
      - MYSQL_PASSWORD=cinema_password
      - MYSQL_DATABASE=cinema_db
      - SERVER_NAME=server2


  webapp3:
    build: .
    ports:
      - "8083:8080"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=cinema_user
      - MYSQL_PASSWORD=cinema_password
      - MYSQL_DATABASE=cinema_db
      - SERVER_NAME=server3

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=cinema_db
      - MYSQL_USER=cinema_user
      - MYSQL_PASSWORD=cinema_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci

volumes:
  mysql_data:
